import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider"
import { Toaster } from "@/components/ui/toaster"

import { headers } from "next/headers";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = headers();
  const pathname = headerList.get("x-current-path");
  const isSignUp=pathname?.includes("/Signup")
  const isLogin=pathname?.includes("/Login")
  const registry = isLogin || isSignUp
  console.log(registry)

  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            
            disableTransitionOnChange
          >
       
           
             <>{children}</>
            
        
        <Toaster />
        </ThemeProvider>

        </body>
    </html>
  );
}
